modLoader="javafml"
loaderVersion="${loader_version_range}"

license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
  modId="wardentools"
  version="1.0.1"
  displayName="ABYSS"
  logoFile="logo.png"
  credits="I pretty much did this by myself"
  authors="Lucifer_C-137"
  description='''Adds the new dimension of ABYSS, with its new biome, mobs, structures, items, lore, etc...'''

[[dependencies.wardentools]]
  modId="forge"
  mandatory=true
  versionRange="${forge_version_range}"
  ordering="NONE"
  side="BOTH"

[[dependencies.wardentools]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"